#Write a function nearly_equal to test whether two strings are nearly equal. Two strings a and b are nearly equal when a can be generated by a single mutation on b.
import mutate
import sys
def nearlyequal(str1,str2):
   mutate.mutate1(str1,str2)
     
  
nearlyequal(sys.argv[1],sys.argv[2])
